builders:
  cubit_impl:
    import: "package:cubit_impl_generator/builder.dart"
    builder_factories: [ "cubitImplBuilder" ]
    build_extensions: { ".dart": [ "cubit_impl.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
